export const products = [
  {
    id: 1,
    name: "HAVIT HV-G92 Gamepad",
    originalPrice: 160,
    discountedPrice: 120,
    discountPercentage: 40,
    rating: 4,
    reviewCount: 88,
    imageUrl: "https://i.postimg.cc/MGvFk4TQ/g92-2-500x500-1.png",
  },
  {
    id: 2,
    name: "AK-900 Wired Keyboard",
    originalPrice: 1160,
    discountedPrice: 960,
    discountPercentage: 35,
    rating: 5,
    reviewCount: 75,
    imageUrl: "https://i.postimg.cc/dQRgy7cp/ak-900-01-500x500-1.png",
    showAddToCart: true,
  },
  {
    id: 3,
    name: "IPS LCD Gaming Monitor",
    originalPrice: 400,
    discountedPrice: 370,
    discountPercentage: 30,
    rating: 5,
    reviewCount: 99,
    imageUrl: "https://i.postimg.cc/NfpVdWMx/Frame-613.png",
  },
  {
    id: 4,
    name: "S-Series Comfort Chair",
    originalPrice: 400,
    discountedPrice: 375,
    discountPercentage: 25,
    rating: 4,
    reviewCount: 99,
    imageUrl:
      "https://i.postimg.cc/VkvhpD0P/sam-moghadam-khamseh-kvmds-Tr-GOBM-unsplash-1.png",
  },
  {
    id: 5,
    name: "Another S-Series Chair",
    originalPrice: 300,
    discountedPrice: 275,
    discountPercentage: 25,
    rating: 5,
    reviewCount: 102,
    imageUrl:
      "https://i.postimg.cc/VkvhpD0P/sam-moghadam-khamseh-kvmds-Tr-GOBM-unsplash-1.png",
  },
  {
    id: 6,
    name: "The north coat",
    originalPrice: 360,
    discountedPrice: 260,
    discountPercentage: 15,
    rating: 5,
    reviewCount: 65,
    imageUrl:
      "https://i.postimg.cc/BbZpDnxf/672462-ZAH9-D-5626-002-100-0000-Light-The-North-Face-x-Gucci-coat-1.png",
  },
  {
    id: 7,
    name: "CANON EOS DSLR Camera",
    // originalPrice: 360,
    discountedPrice: 260,
    // discountPercentage: 15,
    rating: 5,
    reviewCount: 95,
    imageUrl: "https://i.postimg.cc/GpqHt3hy/eos-250d-03-500x500-1.png",
  },
  {
    id: 8,
    name: "ASUS FHD Gaming Laptop",
    // originalPrice: 360,
    discountedPrice: 260,
    // discountPercentage: 15,
    rating: 5,
    reviewCount: 325,
    imageUrl:
      "https://i.postimg.cc/8kFB29tH/Frame-604.png",
  },
  {
    id: 9,
    name: "Curology Product Set ",
    // originalPrice: 360,
    discountedPrice: 500,
    // discountPercentage: 15,
    rating: 4,
    reviewCount: 145,
    imageUrl:
      "https://i.postimg.cc/1RNwC637/curology-j7p-KVQr-TUs-M-unsplash-1.png",
  },
  {
    id: 10,
    name: "GP11 Shooter USB Gamepad",
    // originalPrice: 360,
    discountedPrice: 660,
    // discountPercentage: 15,
    rating: 5,
    reviewCount: 55,
    imageUrl:
      "https://i.postimg.cc/8PQWq5Fp/GP11-PRD3-1.png",
  },
];

export const bestSelling = [
  {
    id: 1,
    name: "The north coat",
    originalPrice: 360,
    discountedPrice: 260,
    discountPercentage: 15,
    rating: 5,
    reviewCount: 65,
    imageUrl:
      "https://i.postimg.cc/BbZpDnxf/672462-ZAH9-D-5626-002-100-0000-Light-The-North-Face-x-Gucci-coat-1.png",
  },
  {
    id: 2,
    name: "Gucci duffle bag",
    originalPrice: 1160,
    discountedPrice: 960,
    discountPercentage: 35,
    rating: 5,
    reviewCount: 65,
    imageUrl: "https://i.postimg.cc/wTvFj3qh/Frame-606.png",
    showAddToCart: true,
  },
  {
    id: 3,
    name: "RGB liquid CPU Cooler",
    originalPrice: 170,
    discountedPrice: 160,
    discountPercentage: 9,
    rating: 4,
    reviewCount: 65,
    imageUrl: "https://i.postimg.cc/vmdWfms2/Frame-610.png",
  },
  {
    id: 4,
    name: "Small BookSelf",
    originalPrice: 400,
    discountedPrice: 360,
    discountPercentage: 9,
    rating: 5,
    reviewCount: 99,
    imageUrl: "https://i.postimg.cc/gj5hJzsD/Frame-612.png",
  },
  {
    id: 5,
    name: "Another S-Series Chair",
    originalPrice: 300,
    discountedPrice: 275,
    discountPercentage: 25,
    rating: 5,
    reviewCount: 102,
    imageUrl:
      "https://i.postimg.cc/VkvhpD0P/sam-moghadam-khamseh-kvmds-Tr-GOBM-unsplash-1.png",
  },
];
