const products = [
    {
      id: 1,
      name: "HAVIT HV-G92 Gamepad",
      originalPrice: 160,
      discountedPrice: 120,
      discountPercentage: 40,
      rating: 4,
      reviewCount: 88,
      imageUrl: "https://i.postimg.cc/MGvFk4TQ/g92-2-500x500-1.png",
    },
    {
      id: 2,
      name: "AK-900 Wired Keyboard",
      originalPrice: 1160,
      discountedPrice: 960,
      discountPercentage: 35,
      rating: 5,
      reviewCount: 75,
      imageUrl: "https://i.imgur.com/VzfL542.png",
      showAddToCart: true,
    },
    {
      id: 3,
      name: "IPS LCD Gaming Monitor",
      originalPrice: 400,
      discountedPrice: 370,
      discountPercentage: 30,
      rating: 5,
      reviewCount: 99,
      imageUrl: "https://i.imgur.com/QZt3fUa.png",
    },
    {
      id: 4,
      name: "S-Series Comfort Chair",
      originalPrice: 400,
      discountedPrice: 375,
      discountPercentage: 25,
      rating: 4,
      reviewCount: 99,
      imageUrl: "https://i.imgur.com/gC235fU.png",
    },
    {
      id: 5,
      name: "Another S-Series Chair",
      originalPrice: 400,
      discountedPrice: 375,
      discountPercentage: 25,
      rating: 5,
      reviewCount: 102,
      imageUrl: "https://i.imgur.com/gC235fU.png",
    },
    {
      id: 6,
      name: "Another S-Series Chair",
      originalPrice: 400,
      discountedPrice: 375,
      discountPercentage: 25,
      rating: 5,
      reviewCount: 102,
      imageUrl: "https://i.imgur.com/gC235fU.png",
    },
    {
      id: 7,
      name: "Another S-Series Chair",
      originalPrice: 400,
      discountedPrice: 375,
      discountPercentage: 25,
      rating: 5,
      reviewCount: 102,
      imageUrl: "https://i.imgur.com/gC235fU.png",
    },
  ];

  export default products;